@startuml
title Play Use Case
state IN_GAME
state " " as INITIAL
state " " as playerChoice <<choice>>
state is_winner <<choice>>
state PutToken

[*] -down-> IN_GAME
IN_GAME --> INITIAL
INITIAL -[#green]-> playerChoice : System request action
playerChoice --> Undo
playerChoice --> Redo
Undo --> INITIAL
Redo --> INITIAL
playerChoice --> INITIAL : Redo
playerChoice -[#green]-> PutToken
PutToken -[#green]-> is_winner
is_winner -[#green]-> Resume : [winner]
is_winner --> INITIAL : change turn
Resume --> [*]

@enduml