@startuml
title "Put token Use Case"

state IN_GAME
state " " as initial
state " " as playerPut
state is_validPut <<choice>>
state " " as tokenPlaced
state " " as winner
state " " as noWinner
state OUT_GAME
state is_winner <<choice>>
[*] -[#green]-> IN_GAME
IN_GAME -[#green]-> initial
note on link #white
	<b>System show</b>
	* Board
	* Color of current player
end note
initial -[#green]-> playerPut
note on link #white : System require Player put token
playerPut -[#green]-> is_validPut
note on link #white : System check if is valid put token

is_validPut -[#green]-> tokenPlaced : [yes]
	tokenPlaced -[#green]-> is_winner
	note on link #white : system show updated board
	is_winner --> winner
	winner --> OUT_GAME
	note on link #white : System show winner menssage
	OUT_GAME --> [*]
	is_winner -[#green]-> noWinner : [no winner]
	noWinner -[#green]-> [*]
	note on link #white
		<b>system allow</b>
		* undo
		* redo
		* put token
	end note
		
is_validPut --> initial
	note on link #white : System show error

@enduml