@startuml
title "Put token Use Case"

state IN_GAME
state PutToken

IN_GAME --> PutToken

state PutToken {
	state " " as zero
	state " " as one
	state " " as two
	state is_validPut <<choice>>
	state " " as tree
	state " " as four
	state " " as five
	state is_winner <<choice>>
	[*] -[#green]-> zero
	zero -[#green]-> one
	note on link #white
		<b>System show</b>
		* Board
		* Color of current player
	end note
	one -[#green]-> two
	note on link #white
		System require Player put token
	end note
	two -[#green]-> is_validPut
	note on link #white
		System check if is valid put token
	end note
	
	is_validPut -[#green]-> tree : [yes]
		tree -[#green]-> is_winner
		note on link #white
			system show updated board
		end note
		is_winner --> four : [winner]
		four --> [*]
		note on link #white
			System show winner menssage
		end note
		is_winner -[#green]-> five
		note on link #white
			System change turn
		end note
		five -[#green]-> [*]
		note on link #white
			<b>system allow</b>
			* undo
			* redo
			* put token
		end note
			
	is_validPut --> one
		note on link #white
			System show error
		end note
}

PutToken --> OUT_GAME

@enduml