@startuml
title Play Use Case
state IN_GAME
state " " as INITIAL
state " " as playerChoice <<choice>>
state is_winner <<choice>>
state PutToken

[*] -down-> IN_GAME
IN_GAME --> INITIAL
INITIAL -[#green]-> playerChoice
note on link #white
	System show available actions
	System requires an action
end note
playerChoice -[#green]-> PutToken
PutToken -[#green]-> is_winner
is_winner -[#green]-> Resume : [winner]

playerChoice --> Undo
playerChoice --> Redo
Undo --> INITIAL
Redo --> INITIAL

is_winner --> INITIAL : system change turn
Resume --> [*]

@enduml