@startuml
title "Start Use Case"

state INITIAL
state " " as one

[*] --> INITIAL
INITIAL --> one
note on link #white
<b>System show</b>
* Welcome Message
* Empty board
end note
one --> IN_GAME
IN_GAME --> [*]

@enduml